from trade.technicals.indicators.generic_indicator import GenericIndicator
from trade.technicals.indicators.moving_averges import MovingAverages
from trade.technicals.indicators.pivot_points import PivotPoints
